theme: jekyll-theme-minimal
##permalink: /:categories/:year/:month/:title/
title: Laiba Mehnaz
description: This is my personal website, covering my work, and my life outside of work. :)
logo: /laibamehnaz.github.io/images/ProfilePhoto_Github.jpg
